// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqlxjqlhazizuszpascd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxbHhqcWxoYXppenVzenBhc2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTE4MTgsImV4cCI6MjA2MjQ2NzgxOH0.fB_qpVze8GneoKkkJ0NbxuYPyrUSuE72cfKQ0um-00Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);